package transformers

import (
	"github.com/wwoytenko/greenfuscator/internal/domains"
	"github.com/wwoytenko/greenfuscator/internal/transformers/faker"
)

type TransformerFabricFunction func(column domains.ColumnMeta, params map[string]string) (domains.Transformer, error)

type TransformerMeta struct {
	Description       string
	ParamsDescription map[string]string
	NewTransformer    TransformerFabricFunction
}

var (
	TransformerMap = map[string]TransformerMeta{
		"Replace": {
			Description: `Replace with value passed through "value" parameter
								Parameters:
									value: value that will be replaced instead of original
			`,
			NewTransformer: NewReplaceTransformer,
		},
		"CreditCard": {
			Description: `Generate fake credit card data using go faker
							Parameters:
								type - type of credit card credentials
									Number                 Generate fake card number
									VendorName             Choose random credit card vendor
									ExpirationDateString   Generated card expiration date string in format {day}/{month}`,
			NewTransformer: faker.NewCreditCardTransformer,
		},
		"Address": {
			Description: `Generate payment data using go faker
									Parameters:
										type - type of payment credentials
											CityPrefix 			City prefix (North, New etc.)
											SecondaryAddress	Second part of the payment with random digits in format "Apt. ###" or "Suite ###"
											State 				USA sate (Alabama, Alaska, etc.)
											StateAbbr			USA sate (AK, AL, etc.)
											CitySuffix 			City prefix (town, port, etc.)
											StreetSuffix 		Street suffix (Alley, Land, etc.)
											BuildingNumber		Random building number inf formats: "####", "###", "##"
											City				City name generated by formats:
																	{{cityPrefix}} {{firstName}}{{citySuffix}}
																	{{cityPrefix}} {{firstName}}
																	{{firstName}}{{citySuffix}}
																	{{lastName}}{{citySuffix}}
											StreetName			Street name generated by formats:
																	{{firstName}} {{streetSuffix}}
																	{{lastName}} {{streetSuffix}}
											StreetAddress		Street payment generated by formats:"
																	{{buildingNumber}} {{streetName}}
																	{{buildingNumber}} {{streetName}} {{secondaryAddress}}
											PostCode			Post code generated by format: #####, #####-####
											Country				Randomly chosen name of real country
											CountryAbbr			Randomly chosen country abbreviature of real country (ABW, NOR, etc.)
											CountryCode 		Randomly chosen country code of real country (DE, CY, etc.)
											Latitude			Randomly generated latitude of the country in format ##.######
											Longitude			Randomly generated longitude of the country in format ##.######
		`,
			NewTransformer: faker.NewAddressTransformer,
		},
		"UUID": {
			Description:    `Generate random UUID using V4 function`,
			NewTransformer: faker.NewUuidTransformer,
		},
		"UserAgent": {
			Description: `Generate user agent
								Parameters:
									agent - Any, Chrome, Firefox, Opera, InternetExplorer, Safari
		`,
			NewTransformer: faker.NewUserAgentTransformer,
		},
	}
)
