common:
  pg_bin_path: "/usr/bin/"
#  pg_bin_path: "/usr/local/opt/postgresql@15/bin"
#  pg_bin_path: "/usr/local/opt/postgresql@16/bin"
  tmp_dir: "/tmp"

log:
  level: "debug"
  format: "text"

storage:
  directory:
    path: "/home/vadim/tmp/pg_dump_test/storage"
#    path: "/Users/vadim/tmp/pg_dump_test/storage/16"
#    path: "/Users/vadim/tmp/pg_dump_test/storage/15"
#  s3:
#    endpoint: "http://localhost:9000"
#    bucket: "testbucket"
#    region: "us-east-1"
#    access_key_id: "Q3AM3UQ867SPQQA43P2F"
#    secret_access_key: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"

dump:
  pg_dump_options:
    dbname: "host=/run/postgresql user=postgres dbname=demo"
#    dbname: "host=localhost user=postgres password=example dbname=demo port=54316"
#    dbname: "host=localhost user=postgres password=example dbname=demo port=54315"
    jobs: 10
    exclude-schema: "(\"teSt\"*|test*)"
    table: "bookings.flights"
    load-via-partition-root: true

  transformation:
    - schema: "bookings"
      name: "flights"
#      query: "select * from bookings.flights limit 1000"
#      columns_type_override:
#        post_code: "int4"
      transformers:
        - name: "RandomDate"
          params:
            min: "2023-01-01 00:00:00.0+03"
            max: "2023-01-02 00:00:00.0+03"
            column: "scheduled_departure"

#        - name: "RandomDate"
#          params:
#            min: "2023-02-02 01:00:00.0+03"
#            max: "2023-03-03 00:00:00.0+03"
#            column: "scheduled_arrival"

        - name: "RegexpReplace"
          params:
            column: "departure_airport"
            regexp: "DME"
            replace: "SVO"

        - name: "RegexpReplace"
          params:
            column: "status"
            regexp: "On Time"
            replace: "Delayed"

#        - name: "RandomDate"
#          params:
#            column: "actual_departure"
#            min: "2023-01-03 01:00:00.0+03"
#            max: "2023-01-04 00:00:00.0+03"
#
#        - name: "RandomDate"
#          params:
#            column: "actual_arrival"
#            min: "2023-01-04 01:00:00.0+03"
#            max: "2023-01-05 00:00:00.0+03"
#
#        - name: "RandomInt"
#          params:
#            column: "post_code"
#            min: "11"
#            max: "99"

        - name: "Replace"
          params:
            column: "post_code"
            value: "54321"

        - name: "TwoDatesGen"
          params:
            column_a: "scheduled_arrival"
            column_b: "actual_arrival"

        - name: "TestTransformer"
          params:
            column: "actual_departure"

    - schema: "bookings"
      name: "aircrafts_data"
      transformers:
        - name: "Json"
          params:
            column: "model"
            operations:
              - operation: "set"
                path: "en"
                value: "Boeing 777-300-2023"
              - operation: "set"
                path: "crewSize"
                value: 10

        - name: "NoiseInt"
          params:
            ratio: 0.9
            column: "range"

restore:
  pg_restore_options:
    jobs: 10
    dbname: "host=/run/postgresql user=postgres dbname=demo_restore"
#    dbname: "host=localhost user=postgres password=example dbname=demo_restore port=54316"
#    dbname: "host=localhost user=postgres password=example dbname=demo_restore port=54315"

  scripts:
    pre-flight:
      - name: "pre-flight test script [1]"
        query: "create table script_test(stage text)"
      - name: "pre-flight test script [1]"
        query: "insert into script_test values('pre-flight')"
    pre-data:
      - name: "pre-data before test script [1]"
        when: "before"
        query: "insert into script_test values('pre-data before')"
      - name: "pre-data after test script [1]"
        when: "after"
        query: "insert into script_test values('pre-data after')"
    data:
      - name: "data before test script [1]"
        when: "before"
        query: "insert into script_test values('data before')"
      - name: "data after test script [1]"
        when: "after"
        query: "insert into script_test values('data after')"
    post-data:
      - name: "post-data before test script [1]"
        when: "before"
        query: "insert into script_test values('post-data before')"
      - name: "post-data after test script [1]"
        when: "after"
        query: "insert into script_test values('post-data after')"
    post-flight:
      - name: "post-flight test script [1]"
        query: "insert into script_test values('post-flight')"

custom_transformers:
  - name: "TestTransformer"
    executable: "/home/vadim/gits/greenmaskio/greenmask/pkg/toolkit/test/test"
    auto_discover: true
  - name: "TwoDatesGen"
    description: "Generate diff between two dates"
    executable: "/home/vadim/gits/greenmaskio/greenmask/internal/db/postgres/transformers/custom/test/example_transformer.sh"
#    executable: "/Users/vadim/gits/greenmaskio/greenmask/internal/db/postgres/transformers/custom/test/example_transformer.sh"
    validate: true
    auto_discover: true
#    validation_timeout: "1ms"
#    row_transformation_timeout: "1ns"
#    args:
#      - '{"name":"TwoDatesGen","description":"Generate diff between two dates","executable":"/usr/bin/true","args":["arg1"],"parameters":[{"name":"column_a","description":"test1","required":true,"is_column":true,"column_properties":{"affected":true,"allowed_types":["date","timestamp","timestamptz"]}},{"name":"column_b","description":"test2","required":true,"is_column":true,"column_properties":{"affected":true,"allowed_types":["date","timestamp","timestamptz"]}}]}'
    parameters:
      - name: "column_a"
        description: "test1"
        required: true
        is_column: true
        column_properties:
          affected: true
          allowed_types:
            - "date"
            - "timestamp"
            - "timestamptz"

      - name: "column_b"
        description: "test2"
        required: true
        is_column: true
        column_properties:
          affected: true
          allowed_types:
            - "date"
            - "timestamp"
            - "timestamptz"
