common:
  bin_path: "/usr/bin"
  storage:
    directory:
      path: "/home/vadim/tmp/pg_dump_test"

restore:
  pg_restore_options:
    verbose: true
    dbname: "host=localhost port=5432 user=postgres dbname=demo_restore"

dump:
  pg_dump_options:
    verbose: true
    dbname: "host=localhost port=5432 user=postgres dbname=test"

  transformers:
    - schema: "public"
      name: "test1"
      columns:
        - name: "title"
          transformer:
            name: "Replace"
            params:
              value: "test"
    - schema: "public"
      name: "cards_test"
      columns:
        - name: "card_number"
          transformer:
            name: "CreditCard"
            params:
              type: "Number"
        - name: "ex_date"
          transformer:
            name: "CreditCard"
            params:
              type: "ExpirationDateString"
        - name: "vendor"
          transformer:
            name: "CreditCard"
            params:
              type: "VendorName"
