version: '3'

services:
  s3:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    ports:
      - ":9000:9000"
    environment:
      - "MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F"
      - "MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/testbucket
      && dd if=/dev/random count=10 > /export/testbucket/test.bin
      && minio server /export'
    network_mode: bridge
