version: '3'

services:
  s3:
    image: minio/minio:latest
    ports:
      - ":9000:9000"
      - ":9001:9001"
    environment:
      - "MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F"
      - "MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/testbucket
      && dd if=/dev/random count=10 > /export/testbucket/test.bin
      && minio server /export --console-address :9001'

  db-16:
    image: postgres:16
    restart: always
    volumes:
      - "/Users/vadim/tmp/pg_dump_test/pgdata/16:/var/lib/postgresql/data"
    ports:
      - "54316:5432"
    environment:
      POSTGRES_PASSWORD: example

  db-15:
    image: postgres:15
    restart: always
    volumes:
      - "/Users/vadim/tmp/pg_dump_test/pgdata/15:/var/lib/postgresql/data"
    ports:
      - "54315:5432"
    environment:
      POSTGRES_PASSWORD: example

  db-14:
    image: postgres:14
    restart: always
    volumes:
      - "/Users/vadim/tmp/pg_dump_test/pgdata/14:/var/lib/postgresql/data"
    ports:
      - "54314:5432"
    environment:
      POSTGRES_PASSWORD: example

  db-13:
    image: postgres:13
    restart: always
    volumes:
      - "/Users/vadim/tmp/pg_dump_test/pgdata/13:/var/lib/postgresql/data"
    ports:
      - "54313:5432"
    environment:
      POSTGRES_PASSWORD: example

  db-12:
    image: postgres:12
    restart: always
    volumes:
      - "/Users/vadim/tmp/pg_dump_test/pgdata/12:/var/lib/postgresql/data"
    ports:
      - "54312:5432"
    environment:
      POSTGRES_PASSWORD: example

  db-11:
    image: postgres:11
    restart: always
    volumes:
      - "/Users/vadim/tmp/pg_dump_test/pgdata/11:/var/lib/postgresql/data"
    ports:
      - "54311:5432"
    environment:
      POSTGRES_PASSWORD: example

  dbs-filler:
    environment:
      PGPASSWORD: "example"
      FILE_DUMP: "demo-small-en.zip"
      TMP_DIR: /tmp/schema
    volumes:
      - "/Users/vadim/tmp/pg_dump_test/schema:/tmp/schema"
    build:
      context: docker/filldb

