version: '3'

services:
  storage:
    image: minio/minio:latest
    ports:
      - ":9000:9000"
      - ":9001:9001"
    environment:
      - "MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F"
      - "MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/adventureworks && minio server /export --console-address :9001'

  db:
    volumes:
      - "/var/lib/postgresql/data"
    image: postgres:16
    ports:
      - "54316:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: [ "CMD", "psql", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 3

  dbs-filler:
    environment:
      PGPASSWORD: "example"
      FILE_DUMP: "demo-small-en.zip"
      TMP_DIR: "/tmp/schema"
    volumes:
      - "/tmp/greenmask_tests:/tmp/schema"
    build:
      context: docker/playground
    depends_on:
      db:
        condition: service_healthy

  greenmask:
    volumes:
      - "/tmp"
    environment:
      PG_BIN_PATH: "/usr/lib/postgresql/16/bin/"
      TEMP_DIR: "/tmp"
      URI: "host=db-16 user=postgres password=example dbname=demo port=5432"
      GREENMASK_BIN_PATH: "/var/lib/greenmask/cmd/greenmask"

      STORAGE_S3_ENDPOINT: "http://storage:9000"
      STORAGE_S3_BUCKET: "testbucket"
      STORAGE_S3_REGION: "us-east-1"
      STORAGE_S3_ACCESS_KEY_ID: "Q3AM3UQ867SPQQA43P2F"
      STORAGE_S3_SECRET_KEY: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      STORAGE_S3_PREFIX: "16"

    build:
      dockerfile: docker/playground/greenmask/Dockerfile
      context: ./
    depends_on:
      dbs-filler:
        condition: service_completed_successfully
