
import yaml
import json
import os

def parse_nav_item(item):
    if isinstance(item, str):
        # File path "foo/bar.md" -> "foo/bar"
        return item.replace(".md", "")
    
    if isinstance(item, dict):
        key = list(item.keys())[0]
        value = item[key]
        
        # Leaf node: "Label": "file.md"
        if isinstance(value, str):
            return {
                "type": "doc",
                "label": key,
                "id": value.replace(".md", "")
            }
        
        # Category node: "Label": [list]
        if isinstance(value, list):
            return {
                "type": "category",
                "label": key,
                "items": [parse_nav_item(i) for i in value]
            }
    
    return None

def main():
    with open("mkdocs.yml", "r") as f:
        data = yaml.safe_load(f)
    
    nav = data.get("nav", [])
    sidebar = [parse_nav_item(item) for item in nav]
    
    # Wrap in sidebars object
    js_content = f"""import type {{SidebarsConfig}} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {{
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{{type: 'autogenerated', dirName: '.'}}],

  // But you can create a sidebar manually
  tutorialSidebar: {json.dumps(sidebar, indent=2)},
}};

export default sidebars;
"""
    
    with open("v1/website/sidebars.ts", "w") as f:
        f.write(js_content)

if __name__ == "__main__":
    main()
