FROM ubuntu:latest

ENV PGPASSWORD=example

ARG DEBIAN_FRONTEND=noninteractive
ARG TMP_DIR=/tmp/schema

RUN apt-get update && apt-get install -y wget && mkdir /tmp/schema

RUN apt-get install --yes --no-install-recommends --no-install-suggests  \
    postgresql \
    postgresql-contrib


RUN printf "#!/bin/bash \
\ncd $TMP_DIR \
\nif [ ! -f demo-big-en.zip ]; then \
\n    wget 'https://edu.postgrespro.com/demo-big-en.zip' \
\nfi\
\nif  psql -U postgres -h db -c 'CREATE DATABASE demo;'; then \
\ngzip -dc demo-small-en.zip | psql -U postgres -d demo -h db \
\nfi\
\npsql -U postgres -h db -c 'DROP DATABASE demo_restore;'\
\npsql -U postgres -h db -c 'CREATE DATABASE demo_restore;'\
" > /script.sh

RUN chmod +x ./script.sh

CMD ["./script.sh"]
