import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
  {
    "type": "category",
    "label": "Documentation",
    "items": [
      {
        "type": "doc",
        "label": "Architecture",
        "id": "architecture"
      },
      {
        "type": "doc",
        "label": "Playground",
        "id": "playground"
      },
      {
        "type": "doc",
        "label": "Installation",
        "id": "installation"
      },
      {
        "type": "doc",
        "label": "Configuration",
        "id": "configuration"
      },
      {
        "type": "category",
        "label": "Commands",
        "items": [
          "commands/index",
          {
            "type": "doc",
            "label": "list-transformers",
            "id": "commands/list-transformers"
          },
          {
            "type": "doc",
            "label": "show-transformer",
            "id": "commands/show-transformer"
          },
          {
            "type": "doc",
            "label": "validate",
            "id": "commands/validate"
          },
          {
            "type": "doc",
            "label": "dump",
            "id": "commands/dump"
          },
          {
            "type": "doc",
            "label": "list-dumps",
            "id": "commands/list-dumps"
          },
          {
            "type": "doc",
            "label": "show-dump",
            "id": "commands/show-dump"
          },
          {
            "type": "doc",
            "label": "restore",
            "id": "commands/restore"
          },
          {
            "type": "doc",
            "label": "delete",
            "id": "commands/delete"
          }
        ]
      },
      {
        "type": "doc",
        "label": "Database subset",
        "id": "database_subset"
      },
      {
        "type": "category",
        "label": "Transformers",
        "items": [
          "built_in_transformers/index",
          {
            "type": "doc",
            "label": "Dynamic parameters",
            "id": "built_in_transformers/dynamic_parameters"
          },
          {
            "type": "doc",
            "label": "Transformation engines",
            "id": "built_in_transformers/transformation_engines"
          },
          {
            "type": "doc",
            "label": "Parameters templating",
            "id": "built_in_transformers/parameters_templating"
          },
          {
            "type": "doc",
            "label": "Transformation conditions",
            "id": "built_in_transformers/transformation_condition"
          },
          {
            "type": "doc",
            "label": "Transformation inheritance",
            "id": "built_in_transformers/transformation_inheritance"
          },
          {
            "type": "category",
            "label": "Standard transformers",
            "items": [
              "built_in_transformers/standard_transformers/index",
              {
                "type": "doc",
                "label": "Cmd",
                "id": "built_in_transformers/standard_transformers/cmd"
              },
              {
                "type": "doc",
                "label": "Dict",
                "id": "built_in_transformers/standard_transformers/dict"
              },
              {
                "type": "doc",
                "label": "Hash",
                "id": "built_in_transformers/standard_transformers/hash"
              },
              {
                "type": "doc",
                "label": "Masking",
                "id": "built_in_transformers/standard_transformers/masking"
              },
              {
                "type": "doc",
                "label": "NoiseDate",
                "id": "built_in_transformers/standard_transformers/noise_date"
              },
              {
                "type": "doc",
                "label": "NoiseFloat",
                "id": "built_in_transformers/standard_transformers/noise_float"
              },
              {
                "type": "doc",
                "label": "NoiseNumeric",
                "id": "built_in_transformers/standard_transformers/noise_numeric"
              },
              {
                "type": "doc",
                "label": "NoiseInt",
                "id": "built_in_transformers/standard_transformers/noise_int"
              },
              {
                "type": "doc",
                "label": "RandomBool",
                "id": "built_in_transformers/standard_transformers/random_bool"
              },
              {
                "type": "doc",
                "label": "RandomChoice",
                "id": "built_in_transformers/standard_transformers/random_choice"
              },
              {
                "type": "doc",
                "label": "RandomDate",
                "id": "built_in_transformers/standard_transformers/random_date"
              },
              {
                "type": "doc",
                "label": "RandomFloat",
                "id": "built_in_transformers/standard_transformers/random_float"
              },
              {
                "type": "doc",
                "label": "RandomNumeric",
                "id": "built_in_transformers/standard_transformers/random_numeric"
              },
              {
                "type": "doc",
                "label": "RandomInt",
                "id": "built_in_transformers/standard_transformers/random_int"
              },
              {
                "type": "doc",
                "label": "RandomString",
                "id": "built_in_transformers/standard_transformers/random_string"
              },
              {
                "type": "doc",
                "label": "RandomUuid",
                "id": "built_in_transformers/standard_transformers/random_uuid"
              },
              {
                "type": "doc",
                "label": "RandomLatitude",
                "id": "built_in_transformers/standard_transformers/random_latitude"
              },
              {
                "type": "doc",
                "label": "RandomLongitude",
                "id": "built_in_transformers/standard_transformers/random_longitude"
              },
              {
                "type": "doc",
                "label": "RandomUnixTimestamp",
                "id": "built_in_transformers/standard_transformers/random_unix_timestamp"
              },
              {
                "type": "doc",
                "label": "RandomDayOfWeek",
                "id": "built_in_transformers/standard_transformers/random_day_of_week"
              },
              {
                "type": "doc",
                "label": "RandomDayOfMonth",
                "id": "built_in_transformers/standard_transformers/random_day_of_month"
              },
              {
                "type": "doc",
                "label": "RandomMonthName",
                "id": "built_in_transformers/standard_transformers/random_month_name"
              },
              {
                "type": "doc",
                "label": "RandomYearString",
                "id": "built_in_transformers/standard_transformers/random_year_string"
              },
              {
                "type": "doc",
                "label": "RandomCentury",
                "id": "built_in_transformers/standard_transformers/random_century"
              },
              {
                "type": "doc",
                "label": "RandomCompany",
                "id": "built_in_transformers/standard_transformers/random_company"
              },
              {
                "type": "doc",
                "label": "RandomTimezone",
                "id": "built_in_transformers/standard_transformers/random_timezone"
              },
              {
                "type": "doc",
                "label": "RandomEmail",
                "id": "built_in_transformers/standard_transformers/random_email"
              },
              {
                "type": "doc",
                "label": "RandomUsername",
                "id": "built_in_transformers/standard_transformers/random_username"
              },
              {
                "type": "doc",
                "label": "RandomPassword",
                "id": "built_in_transformers/standard_transformers/random_password"
              },
              {
                "type": "doc",
                "label": "RandomDomainName",
                "id": "built_in_transformers/standard_transformers/random_domain_name"
              },
              {
                "type": "doc",
                "label": "RandomPerson",
                "id": "built_in_transformers/standard_transformers/random_person"
              },
              {
                "type": "doc",
                "label": "RandomURL",
                "id": "built_in_transformers/standard_transformers/random_url"
              },
              {
                "type": "doc",
                "label": "RandomMac",
                "id": "built_in_transformers/standard_transformers/random_mac"
              },
              {
                "type": "doc",
                "label": "RandomIP",
                "id": "built_in_transformers/standard_transformers/random_ip"
              },
              {
                "type": "doc",
                "label": "RandomWord",
                "id": "built_in_transformers/standard_transformers/random_word"
              },
              {
                "type": "doc",
                "label": "RandomSentence",
                "id": "built_in_transformers/standard_transformers/random_sentence"
              },
              {
                "type": "doc",
                "label": "RandomParagraph",
                "id": "built_in_transformers/standard_transformers/random_paragraph"
              },
              {
                "type": "doc",
                "label": "RandomCCType",
                "id": "built_in_transformers/standard_transformers/random_cc_type"
              },
              {
                "type": "doc",
                "label": "RandomCCNumber",
                "id": "built_in_transformers/standard_transformers/random_cc_number"
              },
              {
                "type": "doc",
                "label": "RandomCurrency",
                "id": "built_in_transformers/standard_transformers/random_currency"
              },
              {
                "type": "doc",
                "label": "RandomAmountWithCurrency",
                "id": "built_in_transformers/standard_transformers/random_amount_with_currency"
              },
              {
                "type": "doc",
                "label": "RandomPhoneNumber",
                "id": "built_in_transformers/standard_transformers/random_phone_number"
              },
              {
                "type": "doc",
                "label": "RandomTollFreePhoneNumber",
                "id": "built_in_transformers/standard_transformers/random_toll_free_phone_number"
              },
              {
                "type": "doc",
                "label": "RandomE164PhoneNumber",
                "id": "built_in_transformers/standard_transformers/random_e164_phone_number"
              },
              {
                "type": "doc",
                "label": "RealAddress",
                "id": "built_in_transformers/standard_transformers/real_address"
              },
              {
                "type": "doc",
                "label": "RegexpReplace",
                "id": "built_in_transformers/standard_transformers/regexp_replace"
              },
              {
                "type": "doc",
                "label": "Replace",
                "id": "built_in_transformers/standard_transformers/replace"
              },
              {
                "type": "doc",
                "label": "SetNull",
                "id": "built_in_transformers/standard_transformers/set_null"
              }
            ]
          },
          {
            "type": "category",
            "label": "Advanced transformers",
            "items": [
              "built_in_transformers/advanced_transformers/index",
              {
                "type": "doc",
                "label": "Json",
                "id": "built_in_transformers/advanced_transformers/json"
              },
              {
                "type": "doc",
                "label": "Template",
                "id": "built_in_transformers/advanced_transformers/template"
              },
              {
                "type": "doc",
                "label": "TemplateRecord",
                "id": "built_in_transformers/advanced_transformers/template_record"
              },
              {
                "type": "category",
                "label": "Custom functions",
                "items": [
                  "built_in_transformers/advanced_transformers/custom_functions/index",
                  {
                    "type": "doc",
                    "label": "Core custom functions",
                    "id": "built_in_transformers/advanced_transformers/custom_functions/core_functions"
                  },
                  {
                    "type": "doc",
                    "label": "Faker function",
                    "id": "built_in_transformers/advanced_transformers/custom_functions/faker_function"
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "type": "doc",
        "label": "About",
        "id": "index"
      }
    ]
  },
  {
    "type": "category",
    "label": "Release notes",
    "items": [
      {
        "type": "doc",
        "label": "Greenmask 0.2.14",
        "id": "release_notes/greenmask_0_2_14"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.13",
        "id": "release_notes/greenmask_0_2_13"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.12",
        "id": "release_notes/greenmask_0_2_12"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.11",
        "id": "release_notes/greenmask_0_2_11"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.10",
        "id": "release_notes/greenmask_0_2_10"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.9",
        "id": "release_notes/greenmask_0_2_9"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.8",
        "id": "release_notes/greenmask_0_2_8"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.7",
        "id": "release_notes/greenmask_0_2_7"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.6",
        "id": "release_notes/greenmask_0_2_6"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.5",
        "id": "release_notes/greenmask_0_2_5"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.4",
        "id": "release_notes/greenmask_0_2_4"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.3",
        "id": "release_notes/greenmask_0_2_3"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.2",
        "id": "release_notes/greenmask_0_2_2"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.1",
        "id": "release_notes/greenmask_0_2_1"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.0",
        "id": "release_notes/greenmask_0_2_0"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.0b2",
        "id": "release_notes/greenmask_0_2_0_b2"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.2.0b1",
        "id": "release_notes/greenmask_0_2_0_b1"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.14",
        "id": "release_notes/greenmask_0_1_14"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.13",
        "id": "release_notes/greenmask_0_1_13"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.12",
        "id": "release_notes/greenmask_0_1_12"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.11",
        "id": "release_notes/greenmask_0_1_11"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.10",
        "id": "release_notes/greenmask_0_1_10"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.9",
        "id": "release_notes/greenmask_0_1_9"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.8",
        "id": "release_notes/greenmask_0_1_8"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.7",
        "id": "release_notes/greenmask_0_1_7"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.6",
        "id": "release_notes/greenmask_0_1_6"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.5",
        "id": "release_notes/greenmask_0_1_5"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.4",
        "id": "release_notes/greenmask_0_1_4"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.3",
        "id": "release_notes/greenmask_0_1_3"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.2",
        "id": "release_notes/greenmask_0_1_2"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.1",
        "id": "release_notes/greenmask_0_1_1"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.0",
        "id": "release_notes/greenmask_0_1_0"
      },
      {
        "type": "doc",
        "label": "Greenmask 0.1.0 Beta",
        "id": "release_notes/greenmask_0_1_0_beta"
      }
    ]
  }
],
};

export default sidebars;
