name: Deploy development documentation (from main branch)

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'

jobs:
  docs:
    uses: ./.github/workflows/docs.yml
